CREATE USER temba WITH SUPERUSER encrypted password 'temba';
CREATE DATABASE temba WITH OWNER temba;
CREATE EXTENSION IF NOT EXISTS postgisi WITH SCHEMA temba;
CREATE EXTENSION IF NOT EXISTS hstore WITH SCHEMA temba;
CREATE EXTENSION IF NOT EXISTS postgis_topology WITH SCHEMA temba;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA temba;

